hyperparameters:
  batch_size: 64
  clip: 1
  dropout: 0.2
  embedding_dim: 128
  hidden_dim: 128
  learning_rate: 0.001
  max_length: 25
  num_epochs: 1
  num_layers: 2
  vocab_size: 30524
model_params:
  caption_model_name: bert-base-uncased
  dropout: 0.3
  out_features: 1024
  resnet_weights: IMAGENET1K_V1
train_test_split:
  random_state: 21
  test_size: 0.2
